name: Deploy Storybook
on:
  workflow_run:
    workflows: ["Build Storybook"]
    types:
      - completed

jobs:
  deploy_storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: rsync deploy storybook
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./storybook-static
          remote_host: ${{ secrets.DEV_REMOTE_HOST }}
          remote_user: ${{ secrets.DEV_REMOTE_USER }}
          remote_key: ${{ secrets.DEV_REMOTE_KEY }}
          remote_path: ${{ secrets.DEV_STORYBOOK_PATH }}