name: Deploy Development

on:
  push:
    branches:
      - development

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      node_version: "20.13.1"

  build_and_deploy_storybook:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Run common steps for storybook deployment
        uses: ./.github/actions/common-steps
        with:
          node_version: "20.13.1"
      - name: Build Storybook
        run: npm run build-storybook
      - name: rsync deploy storybook
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./storybook-static
          remote_host: ${{ secrets.DEV_REMOTE_HOST }}
          remote_user: ${{ secrets.DEV_REMOTE_USER }}
          remote_key: ${{ secrets.DEV_REMOTE_KEY }}
          remote_path: ${{ secrets.DEV_STORYBOOK_PATH }}

  build_and_deploy_project:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Run common steps for project deployment
        uses: ..github/actions/common-steps
        with:
          node_version: "20.13.1"
      - name: Build Project
        run: npm run build
      - name: rsync deploy project
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./dist
          remote_host: ${{ secrets.DEV_REMOTE_HOST }}
          remote_user: ${{ secrets.DEV_REMOTE_USER }}
          remote_key: ${{ secrets.DEV_REMOTE_KEY }}
          remote_path: ${{ secrets.DEV_REMOTE_PATH }}
