name: PullRequest

on:
  pull_request:
    branches:
      - development
      - main

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      node_version: "20.13.1"

  build:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Run common steps for build
        uses: ./.github/actions/common-steps
        with:
          node_version: "20.13.1"
      - name: Build project
        run: npm run build
      - name: Build storybook
        run: npm run build-storybook
